config/routes.rb
Miscmarketv4::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"  } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  # User
  match 'Bubble/:user_id' => 'users#index', :as=>'user_home'
  #match '/users/:user_id/welcome' => 'users#welcome', :as=>'user_welcome_home'
  match '/users/:user_id/verify' => 'users#verify', :as=>'user_verify'
  match '/users/:user_id/social' => 'users#social', :as=>'user_social_add'
  match '/users/:user_id/market/add' => 'markets#add', :as=>'user_market_add'
  match '/users/:user_id/market/confirm' => "markets#confirm", :as => 'user_market_confirm'
  match '/users/:user_id/market/reconfirm' => "markets#reconfirm", :as => 'user_market_reconfirm'
  match '/users/:user_id/markets/verify/:token' => "markets#verify", :as => 'user_market_verify'
  match '/users/:user_id/location/add' => "locations#add", :as => 'user_location_add'
  match '/users/:user_id/location/add/signup' => "locations#sign_up_create", :as => 'user_location_signup_create'
  match '/confirm' => "users#confirm", :as => "user_confirm"
  match '/reconfirm' => "users#reconfirm", :as => "user_reconfirm"

    # iOS
  match '/users/mobile_login', :to => 'users#mobile_login'
  #, :constraints => { :protocol => "https" }
  # http://stackoverflow.com/questions/3634100/rails-3-ssl-deprecation #http://www.simonecarletti.com/blog/2011/05/configuring-rails-3-https-ssl/
  # ssl_required :login # https://github.com/bartt/ssl_requirement

  # User Management
  resources :users

  # Post Management
  resources :posts do
    resources :addresses
    member do
      post :message
    end
  end
  match '/search' => 'posts#search', :as=>'posts_search'

  # Market
  resources :markets

  resources :reposts, :only => [:create]

  # gmail Account Authentication
  match '/gmail_accounts/callback' => 'gmail_accounts#callback', :as => 'gmail_auth_callback'
  match '/gmail_accounts/filter_created' => 'gmail_accounts#filter_created', :as => 'gmail_filter_created'
  resources :gmail_accounts, :only => [:new, :create]

  # Admin
  resources :categories
  resources :locations

  # Session Management for iPhone app
  match '/sessions(.:format)' => 'sessions#create', :as=>'session_create'

  # Miscmarket information sites
  match '/contact' => 'application#contact', :as=>'miscmarket_contact'
  match '/about' => 'application#about', :as=>'miscmarket_about'
  match '/team' => 'application#team', :as=>'miscmarket_team'
  match '/privacy' => 'application#privacy', :as=>'miscmarket_privacy'
  match '/terms' => 'application#terms', :as=>'miscmarket_terms'
  match '/tshirt' => 'application#tshirt', :as=>'miscmarket_tshirt'
  match '/order' => 'application#order', :as=>'miscmarket_tshirt_order'

  # Roots
  match '/' => 'application#index', :as => "home"
  root :to => "application#index", :as => 'root'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :memberships
  has_many :markets_categories
  has_many :post_visibilities

  has_many :users, :through => :memberships
  has_many :posts, :through => :post_visibilities
  has_many :categories, :through => :markets_categories

  has_many :markets_searches
  has_many :search_queries, :through => :markets_searches

  attr_accessible :id, :name, :description

  # Validation.
  validates :name, :presence => true
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  http_basic_authenticate_with :name => "ldevalliere", :password => "miscmarket123", :except => [:add, :confirm, :reconfirm, :verify, :index]

  layout 'user'
  before_filter :authenticate_user!

  # GET /markets
  # GET /markets.json
  def index
    @markets = current_user.confirmed_markets

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @markets }
    end
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
    @market = Market.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @market }
    end
  end

  # GET /markets/new
  # GET /markets/new.json
  def new
    @market = Market.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @market }
    end
  end

  # GET /markets/1/edit
  def edit
    @market = Market.find(params[:id])
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(params[:market])

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render json: @market, status: :created, location: @market }
      else
        format.html { render action: "new" }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /markets/1
  # PUT /markets/1.json
  def update
    @market = Market.find(params[:id])

    respond_to do |format|
      if @market.update_attributes(params[:market])
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market = Market.find(params[:id])
    @market.destroy

    respond_to do |format|
      format.html { redirect_to markets_url }
      format.json { head :ok }
    end
  end

  def add
    if current_user.fb_id == "" && current_user.state == nil
        redirect_to user_social_add_path(current_user)
    else
      @markets = Market.all
      @markets = @markets.sort! { |a,b| a.name <=> b.name }

      if current_user.fb_token != nil
        #Automatically add Facebook networks
        @rest = Koala::Facebook::RestAPI.new(current_user.fb_token)
        @networks = @rest.fql_query("select affiliations from user where uid = me()")

        @networks[0]['affiliations'].each do |network|
          @markets.each do|market|
            if(network['name'] == market.name)
              checker = false;

              current_user.memberships.each do|membership| #check that not already a member
                if(Market.find(membership.market_id).name == market.name)
                  checker = true;
                end
              end

              if checker == false
                current_user.memberships.create(:market_id => market.id, :role => 0, :confirmed_at => Time.now)
              end
            end
          end
        end
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @markets }
    end
  end

  def confirm
    # Request access to a market defined by the :market_id parameter
    @market = Market.find(params[:market_id])

    # Get the email address
    @email = params[:email]
    @sender = "team@miscmarket.org"
    @token = SecureRandom.hex(32)
    confirmed = false;

    # Make sure email corresponds to particular market
    case @email
    when /(\w+\.)?cmu.edu/i;
      if @market.id != 1 #CMU
      end
    when /(\w+\.)?pitt.edu/i;
      if @market.id != 2 #Pitt
      end
    else
      redirect_to(user_market_add_path(current_user), :notice => 'Your email did not correspond with the selected school') and return
    end

    # Check if not already member
    current_user.memberships.each do|membership|
      if(Market.find(membership.market_id).name == @market.name && membership.confirmed_at != nil)
        redirect_to(user_market_add_path(current_user), :notice => "You are already a confirmed member of the " + @market.market + " market") and return
      end
    end

    # Make sure token is unique
    Membership.all.each do |membership|
      if(membership.confirmation_token == @token)
        @token = SecureRandom.hex(32)
      end
    end

    current_user.memberships.create(:market_id => @market.id, :role => 0, :confirmation_token => @token, :email => @email, :confirmation_sent_at => Time.now)
    @message = "Hi " + current_user.first_name + ",\n\nWe just quickly need you to confirm that you belong to the " + @market.name + " market. Please click on the link below:\n\nhttp://localhost:3000/users/" + current_user.id.to_s + "/markets/verify/" + @token + "\n\nThanks,\nThe MiscMarket Team"

    # Send to a specific email defined by the form
    Message.messenger(@email, @sender, @message).deliver
    redirect_to(user_market_add_path(current_user), :notice => "Verification Email to the " + @market.name + " market was successfully sent")
  end

  def reconfirm
    @market = Market.find(params[:market])
    @sender = "team@miscmarket.org"

    current_user.memberships.each do |membership|
      if @market.id == membership.market_id
        @token = membership.confirmation_token
        @email = membership.email
      else
        @token = nil
        @email = nil
      end
    end

    if @token
      @message = "Hi redo" + current_user.first_name + ",\n\nWe just quickly need you to confirm that you belong to the " + @market.name + " market. Please click on the link below:\n\nhttp://localhost:3000/users/" + current_user.id.to_s + "/markets/verify/" + @token + "\n\nThanks,\nThe MiscMarket Team"

      # Send to a specific email defined by the form
      Message.messenger(@email, @sender, @message).deliver

      redirect_to(user_market_add_path(current_user), :notice => "Re-Verification Email to the " + @market.name + " market was successfully sent")
    else
      redirect_to(user_market_add_path(current_user), :notice => "Re-Verification Email to the " + @market.name + " market failed sent")
    end
  end

  def verify
    @memberships  = current_user.memberships
    @market = nil

    @memberships.all.each do |membership|
      if membership.confirmation_token == params[:token]
        membership.confirmation_token = nil;
        membership.confirmed_at = Time.now
        membership.save
        @market = Market.find(membership.market_id)
      end
    end

    @markets = current_user.markets
    @markets = @markets.sort! { |a,b| a.name <=> b.name }

    redirect_to(user_market_add_path(current_user), :notice => "Successfully joined " + @market.name + "!")
  end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_for(@market) do |f| %>
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% @market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markets/add.html.erb
<div class='sign-up-background'>
</div>
<div class='sign-up'>
	<div class='container'>
		<div class='row'>
			<div class='span10 columns sign-up-box offset3'>
				<p class='breadcrumb'>Account - Verify - Social - <span class='active'>Markets</span> - Location</p>
				<div class="page-header"> 
					<h2>Join your Market</h2> 
				</div>

				<% if current_user.fb_id == "" %>
				<p>Seriously, just connect your Facebook account, we'll automatically add all the markets you are already in.</p><%= link_to "Connect your Facebook Account" , user_omniauth_authorize_path(:facebook), :class=>"btn primary" %>
				<% else %>
				<p>We saw that you were affiliated with the following networks and automatically added you to them since you have already verified through Facebook that you are or were once a member in that community.</p>
				<% end  %>
				<p><b><br />Please click on your college below and enter your school address so that we can verify you are part of their network. Send us an email at <%= mail_to "team@miscmarket.org", "team@miscmarket.org" %> if you want to add MiscMarket to your college.<b></p><hr>
					<!-- <h3 class="float_left">Search for your college:</h3><form id="college-search"><input class="xlarge" id="xlInput" name="xlInput" size="30" type="text"></form> -->
				
				<% @markets.each_slice(3) do |slice| %>
					<div class='row market_profiles'>
						<% slice.each do |market| %>
							<div class="span3 columns market_profile">
								<a href="#market_<%= market.id %>_form" class="fancyModal no-underline">
									<div class="market_profile_image">
										<img alt="market <%= market.name %>" class="market_logo" src="/assets/markets/market_<%= market.id %>.png">
									</div>
									<h5><%= market.name %></h5>

								</a>
								<div class="hidden">
									
									<div id="market_<%= market.id %>_form" style="width:400px;height:200px;overflow:auto;">
										<% if current_user.memberships.size == 0 %>
											<h4>Please enter your official school email address</h4>
											<%= form_tag(user_market_confirm_path(:market_id => market.id)) do %>
												<div class="field"> 
													<%= text_field_tag :email %>
												</div> 
													<%= submit_tag 'Send', :class=>"btn large primary verify_market_button" %>
											<% end %>
										<% else %>
											<% current_user.memberships.each do |membership| %>
												<% if membership.market_id == market.id %>
													<% if membership.confirmed_at %>
														<p>Already a member</p>
													<% else %>
														<p>Awaiting confirmation. Please check <%= membership.email %>. Resent Confirmation: <%= link_to "RIGHT NOW", user_market_reconfirm_path(:market => market) %></p>
													<% end %>
												<% else %>
													<%= form_tag(user_market_confirm_path(:market_id => market.id)) do %>
														<div class="field"> 
															<%= label_tag :message_content, 'College Email: Like example@cmu.edu' %><br /> 
															<%= text_field_tag :email %>
														</div> 
														<div class="actions"> 
															<%= submit_tag 'Send' %><p><%= link_to 'Cancel', '#', :class=>"post_message_cancel"%></p>
														</div> 
													<% end %>
												<% end %>
											<% end %>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				<% end %>
				<p><b><br />Send us an email at <%= mail_to "team@miscmarket.org", "team@miscmarket.org" %> if you want to add MiscMarket to your college.<b></p><hr>
				<%= link_to "Add Location", user_location_add_path %>
			</div>
		</div>
	</div>
	<%= render 'shared/sign_up_footer' %>
</div>

app/views/markets/admin.html.erb
<h1>Listing markets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @markets.each do |market| %>
  <tr>
    <td><%= market.name %></td>
    <td><%= market.description %></td>
    <td><%= link_to 'Show', market %></td>
    <td><%= link_to 'Edit', edit_market_path(market) %></td>
    <td><%= link_to 'Destroy', market, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Market', new_market_path %>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render 'form' %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<h1>Listing markets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @markets.each do |market| %>
  <tr>
    <td><%= market.name %></td>
    <td><%= market.description %></td>
    <td><%= link_to 'Show', market %></td>
    <td><%= link_to 'Edit', edit_market_path(market) %></td>
    <td><%= link_to 'Destroy', market, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Market', new_market_path %>

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render 'form' %>

<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @market.name %>
</p>

<p>
  <b>Description:</b>
  <%= @market.description %>
</p>


<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>