config/routes.rb
Miscmarketv4::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"  } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  # User
  match 'Bubble/:user_id' => 'users#index', :as=>'user_home'
  #match '/users/:user_id/welcome' => 'users#welcome', :as=>'user_welcome_home'
  match '/users/:user_id/verify' => 'users#verify', :as=>'user_verify'
  match '/users/:user_id/social' => 'users#social', :as=>'user_social_add'
  match '/users/:user_id/market/add' => 'markets#add', :as=>'user_market_add'
  match '/users/:user_id/market/confirm' => "markets#confirm", :as => 'user_market_confirm'
  match '/users/:user_id/market/reconfirm' => "markets#reconfirm", :as => 'user_market_reconfirm'
  match '/users/:user_id/markets/verify/:token' => "markets#verify", :as => 'user_market_verify'
  match '/users/:user_id/location/add' => "locations#add", :as => 'user_location_add'
  match '/users/:user_id/location/add/signup' => "locations#sign_up_create", :as => 'user_location_signup_create'
  match '/confirm' => "users#confirm", :as => "user_confirm"
  match '/reconfirm' => "users#reconfirm", :as => "user_reconfirm"

    # iOS
  match '/users/mobile_login', :to => 'users#mobile_login'
  #, :constraints => { :protocol => "https" }
  # http://stackoverflow.com/questions/3634100/rails-3-ssl-deprecation #http://www.simonecarletti.com/blog/2011/05/configuring-rails-3-https-ssl/
  # ssl_required :login # https://github.com/bartt/ssl_requirement

  # User Management
  resources :users

  # Post Management
  resources :posts do
    resources :addresses
    member do
      post :message
    end
  end
  match '/search' => 'posts#search', :as=>'posts_search'

  # Market
  resources :markets

  resources :reposts, :only => [:create]

  # gmail Account Authentication
  match '/gmail_accounts/callback' => 'gmail_accounts#callback', :as => 'gmail_auth_callback'
  match '/gmail_accounts/filter_created' => 'gmail_accounts#filter_created', :as => 'gmail_filter_created'
  resources :gmail_accounts, :only => [:new, :create]

  # Admin
  resources :categories
  resources :locations

  # Session Management for iPhone app
  match '/sessions(.:format)' => 'sessions#create', :as=>'session_create'

  # Miscmarket information sites
  match '/contact' => 'application#contact', :as=>'miscmarket_contact'
  match '/about' => 'application#about', :as=>'miscmarket_about'
  match '/team' => 'application#team', :as=>'miscmarket_team'
  match '/privacy' => 'application#privacy', :as=>'miscmarket_privacy'
  match '/terms' => 'application#terms', :as=>'miscmarket_terms'
  match '/tshirt' => 'application#tshirt', :as=>'miscmarket_tshirt'
  match '/order' => 'application#order', :as=>'miscmarket_tshirt_order'

  # Roots
  match '/' => 'application#index', :as => "home"
  root :to => "application#index", :as => 'root'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def index
    if !current_user.nil?
      if current_user.confirmed?
        redirect_to user_home_path(current_user)
      else
        #wait for confirmation
        redirect_to user_verify_path(current_user)
      end
    else
      # user is not logged in at all.

    end
  end

=begin
  #old code
      if current_user.confirmed?
      if current_user.state == 2
        #has finished sign up view
        redirect_to user_home_path(current_user)
      else
        #not finished sign up
      if current_user.fb_id == "" && current_user.state != 1
        redirect_to user_social_add_path(current_user)
      elsif current_user.memberships.size == 0
        #stil needs to add markets
        redirect_to user_market_add_path(current_user)
      elsif current_user.locations.size == 0
        redirect_to user_location_add_path(current_user)
      else
        current_user.state = 2
        current_user.save
        redirect_to user_home_path(current_user)
      end
    end
  else
    #Give verify sign up view
    redirect_to user_verify_path(current_user)
  end
 end

  def after_sign_in_path_for(resource)
    debugger
    if current_user.fb_id != ""
      debugger
      if current_user.memberships.size == 0
        debugger
        redirect_to user_market_add_path(current_user)
      else
        debugger
        redirect_to user_home_path(current_user)
      end
    else
      redirect_to user_social_add_path(current_user)
    end
  end
  end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<script>
$(function(){
	$("a#thumb1").fancybox();
});
</script>
<div class="container_950 bumper">
	<div class='span-24'>
		<div class='span-16'>
			<h1>About</h1>
		</div>
		<div class='span-16'>
			<h2>Imagine Craigslist, Facebook and Google Maps rolled into one app called MiscMarket!</h2>

			<div class="span-16 last">
				<h3>Idea</h3>
			</div>
			<div class="span-16 last">
				<h4>Social Web + Maps + Mobile + Groups = Social Commerce done right!</h4>
				
				<div class="span-16 last">
					<div class="span-8">
						<p>As students, we have had our fair share of headaches to sell those last minute items such as the history book we never read or that lava lamp we bought on a whim. Online second-hand commerce is currently a hassle because it is disorganized and we have to make the difficult decision of trusting a seller we have never met. Furthermore, we are bombarded with ads and search results that are not relevant to our needs.</p>
						</div>
					<div class="span-8 last">
						<%= link_to image_tag('screenshots/thumbShot1.png'), "/images/screenshots/bigShot1.png", :id=>"thumb1" %> 			
					</div>
				</div>
				
				<p>We want to make it easier for you to buy and sell your things online with our simple approach to Social Commerce:</p>
				<ol class='number'>
					<li>
						<h4>Make it Convenient</h4>
						<p>Our recently launched web application is built with an easy-to-use user interface which allows buyers and sellers to post their items to MiscMarket, identify their location through Google maps and market their posts through their social media networks. Our application does the work of three websites and in the future we intend to launch a mobile application for Android and iPhone that will let you easily post to MiscMarket within minutes. We know it is essential for you to get your posts up easily and quickly without the need of a computer. The mobile app will be a core pillar to the MiscMarket information platform to make the application convenient when you are on the go.</p>
					</li>	
					<li>
						<h4>Make it Private</h4>
						<p>MiscMarket uses a closed user group model with social features from Facebook and Twitter. Similar to Facebook, the marketplace you enter is determined by the network you join such as Carnegie Mellon University or University of Pittsburgh. Therefore as a user you benefit from the trust that you have with your network while as a seller you are trusted because you reach a group of people beyond your immediate friends but still within your network!</p>
					</li>
					<li>
						<h4>Make it Relevant</h4>
						<p>MiscMarket is a user-generated and business-generated ad listing website. Unlike the Craigslist of today, we let users create and search classifieds in exclusive groups such as colleges, workplaces, and neighborhoods. Businesses can profit by targeting their advertising in this unique local environment because users are specifically coming to MiscMarket to sell and buy items. Users benefit because our ads will be relevant to their needs and will also allow them to compare second-hand items with similar items offered by businesses, which let’s them make the best choice.</p>
					</li>
				</ol>
				<p>Just check it out for yourself and simply <%= link_to 'sign up', new_user_registration_path, :class=>"content" %> with your CMU.edu or ANDREW.CMU.edu email address and check out what your fellow students are selling.</p>
				<p></p>
			</div>
			<div class="span-16 last">
				<h3>Team</h3>
			</div>
			<div class="span-16 last">
				<p>So who made all of this? MiscMarket was created at Carnegie Mellon by <%= link_to "Louis de Vallière", "http://www.LouisdeValliere.com", :class=>"content" %>, <%= link_to "Sidharth Jayadeep", "http://facebook.com/sidharth.jayadeep", :class => "content" %>, and <%= link_to "Mike Mu", "http://facebook.com/mikemoo", :class => "content" %>.</p>
				<p><%= link_to "More about us", miscmarket_team_path, :class=>"content" %><br /><br /></p>
			</div>
			<div class="span-16 last">
				<h3>Mobile Application</h3>
			</div>
			<div class="span-16 last">

				<div class="span-5">	
					<p>We are working on a mobile app for Android and iPhone that will let you easily post to MiscMarket within minutes. We know it is essential for you to get your posts up easily and quickly without the need of a computer. The mobile app will be a core pillar to the MiscMarket information platform.</p><p>We hope to launch the mobile application sometime after Spring Break.<br /><br /><br /></p>
				</div>
				<div class="span-11 last">
					<%= image_tag "screenshots/iphoneApp.png", :class=>"right" %>
					<%= image_tag "screenshots/androidApp.png", :class=>"right" %>
				</div>
			</div>
		</div>

		<!-- Navigation -->
		<div class='span-8 last welcome_link'>
			<ul class="top">
				<li><%= link_to "home", home_path %></li>
				<li><%= link_to "about", miscmarket_about_path , :class=>"active" %></li>
				<li><%= link_to "blog", "http://blog.miscmarket.org" %></li>
				<li><%= link_to "contact", miscmarket_contact_path %></li>
			</ul>
			<ul class="sub1">
				<li><%= link_to "team", miscmarket_team_path %></li>
				<li><%= link_to "tshirt", miscmarket_tshirt_path %></li>
			</ul>
		</div>
	</div>
</div>
<%= render 'shared/content_footer' %>

app/views/application/contact.html.erb
<%= render 'shared/header_welcome' %>

<div class="container_950 bumper">
	<div class='span-24'>
		<div class='span-16'>
			<h1>Contact</h1>
		</div>
		<div class='span-16'>
			<p>Please feel free to contact us at <%= mail_to "team@miscmarket.org", "team@miscmarket.org", :class=>"content" %>.</p>
			
		</div>
		<div class='span-8 last welcome_link'>
			<ul class="top">
				<li><%= link_to "home", home_path %></li>
				<li><%= link_to "about", miscmarket_about_path %></li>
				<li><%= link_to "blog", "http://blog.miscmarket.org" %></li>
				<li><%= link_to "contact", miscmarket_contact_path, :class=>"active" %></li>
			</ul>
		</div>
	</div>
</div>
<%= render 'shared/content_footer' %>

app/views/application/index.html.erb
<div id="welcome_header">
	<!-- <%= image_tag 'welcome_map.png', :id=>'welcome_map' %> -->
	<div id='welcome_map'></div>
	<div class="container">
		<div id="welcome_content">
			<div id='welcome_info'>
				<%= link_to (image_tag 'logo.png'), home_path, :id=>"logo" %>
				<div id="welcome_slogan">
					<a href="/assets/miscmarketvid_v4-desktop.swf" id="button_movie" class="fancyModal">
						<%= image_tag "icon_play_movie.png", :class=>'button_movie' %>
						<h1 class='button_movie'>What is MiscMarket?</h1>
						<p class='button_movie'>Imagine Craigslist, Facebook and Google Maps rolled into one app.</p>
					</a>
				</div>
			
				<!-- <div id='welcome_movie_container' class="hidden">
					<h2>What's MiscMarket?</h2><a id="welcome_movie_back" href="#">Back</a>			
					<div id='movie'>
						<iframe src="http://player.vimeo.com/video/21574311" width="480" height="260" frameborder="0"></iframe>
						<p>Music Credit: Ghostwriter by RJD2</p>
					</div>
				</div> -->
			
				<div id="facebook_like">
					<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FMiscMarket%2F175052989206405&amp;layout=standard&amp;show_faces=false&amp;width=430&amp;action=like&amp;colorscheme=dark&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:430px; height:35px;" allowTransparency="true"></iframe>
				</div>
			</div>

			<% if( !user_signed_in? ) %>
			<div id='welcome_register'>
				<h1>Sign up now</h1>
				<div id="user_sign_up">
					<div id='fb_add'>
						<div id='fb_add_button'>
							<%= link_to "Connect your Facebook Account" , user_omniauth_authorize_path(:facebook), :class=>"btn primary" %>
						</div>
						<p>Connecting helps everybody in the market see that you exist. We'll never post without your permission.</p>
					</div>
					<div id="email_register">
						<p><%= link_to "Or sign up through Email", new_user_registration_path %></p>
					</div>
					<%= link_to (image_tag('appStore.png', :id=>"app-store")), home_path , :id=>"app-store" %>
				
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

<div class='container bumper'>
	<div class='row'>
		<div id="user_login" class='span11 columns'>				
			<% if(!user_signed_in?) %>
			<%= form_for("user", :url => user_session_path) do |f| %>
			<div id="login_details" class='login_container'>
				<table id='login_table'>
					<!-- <tr>
						<td><%= f.label :email, :id=>"email_label" %></td>
						<td><%= f.label :password, :id=>"password_label" %></td>
					</tr>-->
					<tr>
						<td><%= f.text_field(:email,:size => 21, :placeholder => "Email") %></td>
						<td><%= f.password_field(:password,:size => 21, :placeholder => "Password") %></td>
					</tr>
					<tr>
						<td><%= f.check_box :remember_me %><p><%= f.label :remember_me, :id=>"remember_me_label" %></p></td>
						<td>
							<p><%= link_to "Forgot", new_password_path("user"), :id=>"forgot_password" %> or
							<%= link_to "resend Confirmation?", new_user_confirmation_path, :id=>"get_confirmation" %></p>
						</td>
					</tr>
				</table>	
				<div id="submit_button">
					<%= f.submit 'Login', :class=>'btn large primary', :id=>"submit_button_input" %>
				</div>
			</div>
			<% end %>
			<% else %>
			<div class='columns'>
				<h1>Please confirm email address</h1>
			</div>
			<div class='columns'>
				<p>You are logged in, but you still need to confirm the email address you signed up with: <span class="bold"><%= current_user.email %></span></p>
				<p>Click <%= link_to "here", new_user_confirmation_path, :class=>"content" %> to resend confirmation email again or <%= link_to('logout', destroy_user_session_path, :method => 'delete', :class=>"content") %> 
				 to login with different user credentials.</p>
				<p>Please feel free to contact us at <%= mail_to "team@miscmarket.org", "team@miscmarket.org", :class=>"content" %> if you need any help or have trouble.</p>
			</div>
			<% end%>
		</div>
	</div>
</div>
<%= render 'shared/content_footer' %>