config/routes.rb
Miscmarketv4::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"  } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  # User
  match 'Bubble/:user_id' => 'users#index', :as=>'user_home'
  #match '/users/:user_id/welcome' => 'users#welcome', :as=>'user_welcome_home'
  match '/users/:user_id/verify' => 'users#verify', :as=>'user_verify'
  match '/users/:user_id/social' => 'users#social', :as=>'user_social_add'
  match '/users/:user_id/market/add' => 'markets#add', :as=>'user_market_add'
  match '/users/:user_id/market/confirm' => "markets#confirm", :as => 'user_market_confirm'
  match '/users/:user_id/market/reconfirm' => "markets#reconfirm", :as => 'user_market_reconfirm'
  match '/users/:user_id/markets/verify/:token' => "markets#verify", :as => 'user_market_verify'
  match '/users/:user_id/location/add' => "locations#add", :as => 'user_location_add'
  match '/users/:user_id/location/add/signup' => "locations#sign_up_create", :as => 'user_location_signup_create'
  match '/confirm' => "users#confirm", :as => "user_confirm"
  match '/reconfirm' => "users#reconfirm", :as => "user_reconfirm"

    # iOS
  match '/users/mobile_login', :to => 'users#mobile_login'
  #, :constraints => { :protocol => "https" }
  # http://stackoverflow.com/questions/3634100/rails-3-ssl-deprecation #http://www.simonecarletti.com/blog/2011/05/configuring-rails-3-https-ssl/
  # ssl_required :login # https://github.com/bartt/ssl_requirement

  # User Management
  resources :users

  # Post Management
  resources :posts do
    resources :addresses
    member do
      post :message
    end
  end
  match '/search' => 'posts#search', :as=>'posts_search'

  # Market
  resources :markets

  resources :reposts, :only => [:create]

  # gmail Account Authentication
  match '/gmail_accounts/callback' => 'gmail_accounts#callback', :as => 'gmail_auth_callback'
  match '/gmail_accounts/filter_created' => 'gmail_accounts#filter_created', :as => 'gmail_filter_created'
  resources :gmail_accounts, :only => [:new, :create]

  # Admin
  resources :categories
  resources :locations

  # Session Management for iPhone app
  match '/sessions(.:format)' => 'sessions#create', :as=>'session_create'

  # Miscmarket information sites
  match '/contact' => 'application#contact', :as=>'miscmarket_contact'
  match '/about' => 'application#about', :as=>'miscmarket_about'
  match '/team' => 'application#team', :as=>'miscmarket_team'
  match '/privacy' => 'application#privacy', :as=>'miscmarket_privacy'
  match '/terms' => 'application#terms', :as=>'miscmarket_terms'
  match '/tshirt' => 'application#tshirt', :as=>'miscmarket_tshirt'
  match '/order' => 'application#order', :as=>'miscmarket_tshirt_order'

  # Roots
  match '/' => 'application#index', :as => "home"
  root :to => "application#index", :as => 'root'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :posts
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout :resolve_layout
  before_filter :authenticate_user!

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end

  def add
    if current_user.markets.size == 0
      redirect_to user_market_add_path, notice: 'You need to join a market first'
    end

    @location = Location.new

    # User has complete sign up process
    current_user.state = 2
    current_user.save

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  def sign_up_create
    @location = Location.new(params[:location])
    @location.user_id = current_user.id
    @location.available = true

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Welcome to MiscMarket' }
      else
        format.html { redirect_to user_location_add_path(@location), notice: 'Could not save your address, please check it.'}
      end
    end
  end

  private
  def resolve_layout
    case action_name
    when "add"
      "sign_up"
    else
      "user"
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_1 %><br />
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br />
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/add.html.erb
<div class='sign-up-background'>
</div>
<div class='sign-up'>
	<div class='container'>
		<div class='row'>
			<div class='span10 columns sign-up-box offset3'>
				<p class='breadcrumb'>Account - Verify - Social - Markets - <span class='active'>Location</span></p>
				
				<div class="page-header"> 
					<h2>Where's home? <small>Optional</small></h2> 
				</div>
				
				<p>We won't share this with anybody except the people in your network.</p>
				
				<div id="map_canvas"></div>
				
				<%= form_for(@location, :url => user_location_signup_create_path) do |f| %>

				<div class="clearfix" id="user_first_name_div"> 
					<%= f.label :address_1 %>
					<div class="input"> 
						<%= f.text_field :address_1 %>
						<span id="user_first_name_hint" class="help-inline hidden">We need your first name</span>
					</div> 
				</div> <!-- /clearfix -->

				<div class="clearfix" id="user_last_name_div"> 
					<%= f.label :address_2 %>
					<div class="input"> 
						<%= f.text_field :address_2 %>
						<span id="user_last_name_hint" class="help-inline hidden">We also need your last name</span>
					</div> 
				</div> <!-- /clearfix -->

				<div class="clearfix" id="user_email_div"> 
					<%= f.label :city %>
					<div class="input"> 
						<%= f.text_field :city %>
						<span class="help-inline hidden" id="user_email_hint_missing">We want to keep in touch</span>
						<span class="help-inline hidden" id="user_email_hint_taken">Email used, <%= link_to "forget your password?", new_password_path("user") %></span>
						 <% if @location.errors.any? %>
							<script>
							// Bad
							$('.field_with_errors').removeClass('field_with_errors');
							
							$("#user_email_div").addClass("error");
							$("#user_email_hint_taken").fadeIn();							
							</script>
						 <% end %>
						
						<span class="help-inline hidden" id="user_email_hint_invalid">That doesn't look valid...</span>
					</div> 
				</div> <!-- /clearfix -->

				<div class="clearfix" id="user_password_div"> 
					<%= f.label :zipcode %>
					<div class="input"> 
						<%= f.password_field :zipcode %>
						<span class="help-inline hidden" id="user_password_hint_missing">Missing your super secret password</span>
						<span class="help-inline hidden" id="user_password_hint_invalid">Needs to be at least 6 characters</span>
					</div> 
				</div> <!-- /clearfix -->

				<div class='hidden'>
					<%= f.text_field :country %>
					<%= f.text_field :latitude %>
					<%= f.text_field :longitude %>
				</div>

				<div class="actions submit"> 
					<%= f.submit "Add Location", :class=>"btn primary" %>
				</div>
				<% end %>
				
				<%= link_to "Back", user_market_add_path, :class=>"btn large" %>
				<%= link_to "Finish", user_home_path, :class=>"btn large primary" %>
			</div>
		</div>
	</div>
	<%= render 'shared/sign_up_footer' %>
</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>City</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Available</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.user_id %></td>
    <td><%= location.address_1 %></td>
    <td><%= location.address_2 %></td>
    <td><%= location.city %></td>
    <td><%= location.zipcode %></td>
    <td><%= location.country %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= location.available %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @location.user_id %>
</p>

<p>
  <b>Address 1:</b>
  <%= @location.address_1 %>
</p>

<p>
  <b>Address 2:</b>
  <%= @location.address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @location.zipcode %>
</p>

<p>
  <b>Country:</b>
  <%= @location.country %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Available:</b>
  <%= @location.available %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>